apiVersion: v1
kind: Service
metadata:
  labels:
  name: ghost-nodeport
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 2368
    protocol: TCP
    targetPort: 2368
    nodePort: 32100
  selector:
    app: ghost