apiVersion: v1
kind: Service
metadata:
  name: ghost-cluster
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 2368
  #    nodePort: 32100
  selector:
    app: ghost
