apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  spec:
  replicas: 3
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost
          ports:
            - containerPort: 2368
